# Generated by Django 4.2.8 on 2025-12-03 16:12

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('campaigns_module', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Investment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(100)])),
                ('payment_method', models.CharField(choices=[('crypto', 'Cryptocurrency (MetaMask)'), ('telebirr', 'Telebirr'), ('cbe', 'Commercial Bank of Ethiopia'), ('awash', 'Awash Bank'), ('dashen', 'Dashen Bank'), ('abyssinia', 'Bank of Abyssinia'), ('other', 'Other')], max_length=20)),
                ('transaction_hash', models.CharField(blank=True, max_length=66, null=True)),
                ('payment_reference', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('failed', 'Failed'), ('refunded', 'Refunded')], default='pending', max_length=20)),
                ('blockchain_tx_hash', models.CharField(blank=True, help_text='Blockchain transaction hash for on-chain recording', max_length=66, null=True)),
                ('blockchain_recorded_at', models.DateTimeField(blank=True, help_text='Timestamp when investment was recorded on blockchain', null=True)),
                ('yield_earned', models.DecimalField(decimal_places=2, default=0, help_text='Yield earned from DeFi farming', max_digits=15)),
                ('nft_token_id', models.CharField(blank=True, max_length=100, null=True)),
                ('nft_minted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('refunded_at', models.DateTimeField(blank=True, null=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investments', to='campaigns_module.campaign')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Investment',
                'verbose_name_plural': 'Investments',
                'db_table': 'investments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('transaction_id', models.CharField(max_length=100, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('provider', models.CharField(choices=[('telebirr', 'Telebirr'), ('cbe', 'CBE'), ('awash', 'Awash Bank'), ('dashen', 'Dashen Bank'), ('abyssinia', 'Bank of Abyssinia')], max_length=20)),
                ('phone_number', models.CharField(blank=True, max_length=20)),
                ('account_number', models.CharField(blank=True, max_length=50)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('error_message', models.TextField(blank=True)),
                ('provider_reference', models.CharField(blank=True, max_length=100)),
                ('provider_response', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='campaigns_module.campaign')),
                ('investment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='investments.investment')),
            ],
            options={
                'verbose_name': 'Payment',
                'verbose_name_plural': 'Payments',
                'db_table': 'payments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NFTShareCertificate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('token_id', models.CharField(max_length=100, unique=True)),
                ('contract_address', models.CharField(max_length=42)),
                ('token_uri', models.URLField(blank=True, max_length=500, null=True)),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('voting_weight', models.DecimalField(decimal_places=6, default=0, max_digits=10)),
                ('mint_tx_hash', models.CharField(max_length=66)),
                ('minted_at', models.DateTimeField(auto_now_add=True)),
                ('investment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='nft_certificate', to='investments.investment')),
            ],
            options={
                'verbose_name': 'NFT Share Certificate',
                'verbose_name_plural': 'NFT Share Certificates',
                'db_table': 'nft_share_certificates',
                'ordering': ['-minted_at'],
            },
        ),
    ]
