# Generated by Django 4.2.8 on 2025-12-03 16:12

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('issuers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('funding_goal', models.DecimalField(decimal_places=2, help_text='Funding goal in ETB', max_digits=15, validators=[django.core.validators.MinValueValidator(1000)])),
                ('current_funding', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('duration', models.IntegerField(help_text='Campaign duration in days', validators=[django.core.validators.MinValueValidator(30), django.core.validators.MaxValueValidator(180)])),
                ('success_threshold', models.DecimalField(decimal_places=2, default=75, help_text='Success threshold percentage (default 75%)', max_digits=5)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending Approval'), ('approved', 'Approved'), ('active', 'Active'), ('successful', 'Successful'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('smart_contract_address', models.CharField(blank=True, max_length=42, null=True)),
                ('deployment_tx_hash', models.CharField(blank=True, max_length=66, null=True)),
                ('deployed_on_blockchain', models.BooleanField(default=False)),
                ('blockchain_deployed_at', models.DateTimeField(blank=True, null=True)),
                ('ipfs_document_hash', models.CharField(blank=True, help_text='IPFS hash for campaign documents', max_length=100, null=True)),
                ('approved', models.BooleanField(default=False)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('funds_released', models.BooleanField(default=False)),
                ('funds_released_at', models.DateTimeField(blank=True, null=True)),
                ('funds_release_tx_hash', models.CharField(blank=True, max_length=66, null=True)),
                ('investor_count', models.IntegerField(default=0)),
                ('total_shares_issued', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_campaigns', to=settings.AUTH_USER_MODEL)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaigns', to='issuers.company')),
            ],
            options={
                'verbose_name': 'Campaign',
                'verbose_name_plural': 'Campaigns',
                'db_table': 'campaigns',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CampaignUpdate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('posted_at', models.DateTimeField(auto_now_add=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='updates', to='campaigns_module.campaign')),
            ],
            options={
                'verbose_name': 'Campaign Update',
                'verbose_name_plural': 'Campaign Updates',
                'db_table': 'campaign_updates',
                'ordering': ['-posted_at'],
            },
        ),
        migrations.CreateModel(
            name='CampaignDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('document_type', models.CharField(choices=[('business_plan', 'Business Plan'), ('financial_statement', 'Financial Statement'), ('legal_document', 'Legal Document'), ('other', 'Other')], max_length=30)),
                ('file_url', models.URLField(max_length=500)),
                ('ipfs_hash', models.CharField(blank=True, max_length=100, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='campaigns_module.campaign')),
            ],
            options={
                'verbose_name': 'Campaign Document',
                'verbose_name_plural': 'Campaign Documents',
                'db_table': 'campaign_documents',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.AddIndex(
            model_name='campaign',
            index=models.Index(fields=['status'], name='campaigns_status_a03570_idx'),
        ),
        migrations.AddIndex(
            model_name='campaign',
            index=models.Index(fields=['company'], name='campaigns_company_8546b8_idx'),
        ),
        migrations.AddIndex(
            model_name='campaign',
            index=models.Index(fields=['smart_contract_address'], name='campaigns_smart_c_a46bd7_idx'),
        ),
    ]
