# Generated by Django 4.2.8 on 2026-01-07 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns_module', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='min_investment',
            field=models.DecimalField(decimal_places=2, default=100, help_text='Minimum investment amount', max_digits=15),
        ),
    ]
