# Generated by Django 4.2.8 on 2026-01-07 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns_module', '0002_campaign_min_investment'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='max_investment',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Maximum investment amount (optional)', max_digits=15, null=True),
        ),
    ]
