# Generated by Django 4.2.8 on 2025-12-03 16:12

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('admin', 'Administrator'), ('compliance_officer', 'Compliance Officer'), ('custodian', 'Custodian'), ('regulator', 'Regulator'), ('issuer', 'Campaign Issuer'), ('investor', 'Investor')], default='investor', max_length=50)),
                ('wallet_address', models.CharField(blank=True, max_length=42, null=True, unique=True)),
                ('kyc_level', models.CharField(choices=[('none', 'Not Verified'), ('basic', 'Basic KYC'), ('enhanced', 'Enhanced KYC'), ('premium', 'Premium KYC')], default='none', max_length=20)),
                ('kyc_verified', models.BooleanField(default=False)),
                ('kyc_verified_at', models.DateTimeField(blank=True, null=True)),
                ('aml_risk_score', models.IntegerField(default=0, help_text='AML risk score (0-100)', validators=[django.core.validators.MinValueValidator(0)])),
                ('vc_hash', models.CharField(blank=True, help_text='Keycloak Verifiable Credential hash', max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'db_table': 'users',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('tin_number', models.CharField(help_text='Tax Identification Number', max_length=50, unique=True)),
                ('sector', models.CharField(choices=[('agriculture', 'Agriculture'), ('technology', 'Technology'), ('manufacturing', 'Manufacturing'), ('healthcare', 'Healthcare'), ('education', 'Education'), ('retail', 'Retail'), ('finance', 'Finance'), ('energy', 'Energy'), ('transport', 'Transport'), ('other', 'Other')], max_length=50)),
                ('registration_year', models.IntegerField(blank=True, null=True)),
                ('verified', models.BooleanField(default=False)),
                ('blockchain_address', models.CharField(blank=True, max_length=42, null=True)),
                ('ipfs_document_hash', models.CharField(blank=True, help_text='IPFS hash for Information Memorandum', max_length=100, null=True)),
                ('registered_on_blockchain', models.BooleanField(default=False)),
                ('blockchain_tx_hash', models.CharField(blank=True, max_length=66, null=True)),
                ('blockchain_registered_at', models.DateTimeField(blank=True, null=True)),
                ('has_active_campaign', models.BooleanField(default=False, help_text='True if company has an active campaign (single-campaign rule)')),
                ('active_campaign_id', models.UUIDField(blank=True, help_text='ID of currently active campaign', null=True)),
                ('last_campaign_year', models.IntegerField(blank=True, help_text='Year of last campaign (one campaign per year rule)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='companies', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Company',
                'verbose_name_plural': 'Companies',
                'db_table': 'companies',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='KYCDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('document_type', models.CharField(choices=[('national_id', 'National ID'), ('passport', 'Passport'), ('driving_license', 'Driving License'), ('business_license', 'Business License'), ('tax_certificate', 'Tax Certificate'), ('incorporation_cert', 'Certificate of Incorporation'), ('proof_of_address', 'Proof of Address'), ('financial_statement', 'Financial Statement'), ('other', 'Other')], max_length=50)),
                ('document_number', models.CharField(blank=True, max_length=100)),
                ('document_file', models.FileField(upload_to='kyc_documents/%Y/%m/')),
                ('ipfs_hash', models.CharField(blank=True, max_length=100, null=True)),
                ('ocr_processed', models.BooleanField(default=False)),
                ('ocr_data', models.JSONField(blank=True, null=True)),
                ('ai_verification_score', models.DecimalField(blank=True, decimal_places=2, help_text='AI verification confidence score (0-100)', max_digits=5, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('verified', 'Verified'), ('rejected', 'Rejected'), ('expired', 'Expired')], default='pending', max_length=20)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('issue_date', models.DateField(blank=True, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='kyc_documents', to='issuers.company')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kyc_documents', to=settings.AUTH_USER_MODEL)),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'KYC Document',
                'verbose_name_plural': 'KYC Documents',
                'db_table': 'kyc_documents',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='IssuerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(blank=True, max_length=20)),
                ('business_email', models.EmailField(blank=True, max_length=254)),
                ('website', models.URLField(blank=True)),
                ('street_address', models.TextField(blank=True)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('state_province', models.CharField(blank=True, max_length=100)),
                ('postal_code', models.CharField(blank=True, max_length=20)),
                ('country', models.CharField(default='Ethiopia', max_length=100)),
                ('business_description', models.TextField(blank=True)),
                ('years_in_operation', models.IntegerField(blank=True, null=True)),
                ('number_of_employees', models.IntegerField(blank=True, null=True)),
                ('annual_revenue', models.DecimalField(blank=True, decimal_places=2, help_text='Annual revenue in ETB', max_digits=15, null=True)),
                ('compliance_officer_name', models.CharField(blank=True, max_length=255)),
                ('compliance_officer_email', models.EmailField(blank=True, max_length=254)),
                ('onboarding_completed', models.BooleanField(default=False)),
                ('onboarding_step', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issuer_profiles', to='issuers.company')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='issuer_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Issuer Profile',
                'verbose_name_plural': 'Issuer Profiles',
                'db_table': 'issuer_profiles',
            },
        ),
    ]
