# Generated by Django 4.2.8 on 2026-01-14 13:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('campaigns_module', '0003_campaign_max_investment'),
    ]

    operations = [
        migrations.CreateModel(
            name='DAOProposal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('blockchain_id', models.CharField(blank=True, db_index=True, max_length=66, null=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('proposal_type', models.CharField(choices=[('campaign', 'Campaign Decision'), ('platform', 'Platform Upgrade'), ('treasury', 'Treasury Allocation'), ('governance', 'Governance Change')], default='platform', max_length=20)),
                ('proposer_address', models.CharField(max_length=42)),
                ('target_address', models.CharField(blank=True, max_length=42, null=True)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('voting_duration', models.IntegerField(default=86400)),
                ('start_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_time', models.DateTimeField()),
                ('votes_for', models.DecimalField(decimal_places=0, default=0, max_digits=20)),
                ('votes_against', models.DecimalField(decimal_places=0, default=0, max_digits=20)),
                ('quorum', models.DecimalField(decimal_places=0, default=1000, max_digits=20)),
                ('voting_power_required', models.DecimalField(decimal_places=0, default=100, max_digits=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('passed', 'Passed'), ('failed', 'Failed'), ('executed', 'Executed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('executed', models.BooleanField(default=False)),
                ('executed_at', models.DateTimeField(blank=True, null=True)),
                ('transaction_hash', models.CharField(blank=True, max_length=66, null=True)),
                ('execution_hash', models.CharField(blank=True, max_length=66, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('synced_at', models.DateTimeField(blank=True, null=True)),
                ('campaign', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dao_proposals', to='campaigns_module.campaign')),
                ('proposer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dao_proposals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DAOVote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('voter_address', models.CharField(db_index=True, max_length=42)),
                ('support', models.BooleanField()),
                ('voting_power', models.DecimalField(decimal_places=0, max_digits=20)),
                ('transaction_hash', models.CharField(blank=True, max_length=66, null=True)),
                ('cast_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('synced_at', models.DateTimeField(blank=True, null=True)),
                ('proposal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='dao.daoproposal')),
                ('voter', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dao_votes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-cast_at'],
                'unique_together': {('proposal', 'voter_address')},
            },
        ),
    ]
