# Generated by Django 4.2.8 on 2025-12-03 16:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('campaigns_module', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FundEscrow',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('total_escrowed', models.DecimalField(decimal_places=2, default=0, help_text='Total amount held in escrow', max_digits=15)),
                ('status', models.CharField(choices=[('escrowed', 'Escrowed'), ('released', 'Released'), ('refunded', 'Refunded')], default='escrowed', max_length=20)),
                ('escrow_contract_address', models.CharField(blank=True, max_length=42, null=True)),
                ('funds_released', models.BooleanField(default=False)),
                ('funds_released_at', models.DateTimeField(blank=True, null=True)),
                ('release_tx_hash', models.CharField(blank=True, max_length=66, null=True)),
                ('released_to_address', models.CharField(blank=True, max_length=42, null=True)),
                ('refund_initiated', models.BooleanField(default=False)),
                ('refund_completed', models.BooleanField(default=False)),
                ('refund_tx_hash', models.CharField(blank=True, max_length=66, null=True)),
                ('refunded_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('campaign', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='escrow', to='campaigns_module.campaign')),
            ],
            options={
                'verbose_name': 'Fund Escrow',
                'verbose_name_plural': 'Fund Escrows',
                'db_table': 'fund_escrows',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RefundTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('tx_hash', models.CharField(max_length=66)),
                ('refunded_at', models.DateTimeField(auto_now_add=True)),
                ('escrow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refund_transactions', to='escrow.fundescrow')),
                ('investor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Refund Transaction',
                'verbose_name_plural': 'Refund Transactions',
                'db_table': 'refund_transactions',
                'ordering': ['-refunded_at'],
            },
        ),
        migrations.AddIndex(
            model_name='fundescrow',
            index=models.Index(fields=['campaign'], name='fund_escrow_campaig_2f1b83_idx'),
        ),
        migrations.AddIndex(
            model_name='fundescrow',
            index=models.Index(fields=['status'], name='fund_escrow_status_3f7dec_idx'),
        ),
    ]
